# Generated by Django 4.1.3 on 2022-11-21 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repaso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repaso',
            name='fecha_repaso',
            field=models.DateField(default=datetime.date(2022, 11, 21)),
        ),
    ]
